version: '3'
services:
  dbserver-wordpress:
    restart: always
    hostname: dbserver-wordpress
    image: mysql:5.7
    networks:
      - wp-net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"

networks:
  wp-net:
    external: true
