version: '3'
services:
  dbserver-wordpress:
    restart: always
    hostname: dbserver-wordpress
    image: mysql:5.7
    networks:
      - wp-net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
    volumes:
      - "/data:/var/lib/mysql"
  
  phpmyadmin:
    restart: always
    image: phpmyadmin
    networks:
      - wp-net
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: "${PMA_ARBITRARY}"

  webserver-wordpress:
    restart: always
    image: wordpress:latest
    networks:
      - wp-net
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    volumes:
      - "/wpsite:/var/www/html"
    depends_on:
          - dbserver-wordpress

networks:
  wp-net:
    external: true
